Document: dandelion
Title: Debian dandelion Manual
Author: <insert document author here>
Abstract: This manual describes what dandelion is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dandelion/dandelion.sgml.gz

Format: postscript
Files: /usr/share/doc/dandelion/dandelion.ps.gz

Format: text
Files: /usr/share/doc/dandelion/dandelion.text.gz

Format: HTML
Index: /usr/share/doc/dandelion/html/index.html
Files: /usr/share/doc/dandelion/html/*.html
